os: linux
dist: bionic

language: node_js
node_js:
  - "stable"

cache:
  directories:
  - node_modules
  - ~/.cache

addons:
  firefox: latest
  chrome: stable

install:
  - npm install cypress

before_script:
  - google-chrome --version
  - firefox --version
  - cypress info

script:
  - cypress run --browser chrome --headless --spec "cypress/integration/test.js"
