os: linux
dist: bionic

language: node_js
node_js:
  - "stable"

cache:
  directories:
  - node_modules

addons:
  firefox: latest
  chrome: stable

script:
  - npm run cy:run --browser chrome --headless --spec "cypress/integration/test.js"
